version: '3.9'

services:

  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
# services:
#   db:
#     image: postgres:14.10
#     restart: always
#     container_name: postgresql
#     volumes:
#       - ./data/db:/var/lib/postgresql/data
    
#     environment:
#       - DATABASE_HOST=127.0.0.1
#       - POSTGRES_DB=postgres
#       - POSTGRES_USER=postgres
#       - POSTGRES_PASSWORD=postgres
#     ports:
#       - "5433:5432"
  
#   pgadmin:
#     image: dpage/pgadmin4
#     container_name: pgadmin
#     environment:
#       - PGADMIN_DEFAULT_EMAIL=admin@admin.com
#       - PGADMIN_DEFAULT_PASSWORD=admin
#     ports:
#       - "80:80"
#     depends_on:
#       - db
  
#   web:
#     build: .
#     container_name: django
#     command: python3 manage.py runserver 
#     volumes:
#       - .:/app
#     ports:
#       - "8000:8000"
#     environment:
#       - POSTGRES_NAME=postgres
#       - POSTGRES_USER=postgres
#       - POSTGRES_PASSWORD=postgres
#     depends_on:
#       - db