# Generated by Django 5.0.4 on 2024-04-19 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehiculo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Infraccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_infringement', models.DateTimeField()),
                ('comment', models.TextField()),
                ('placa_patente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infraccionlist', to='vehiculo.vehiculo')),
            ],
        ),
    ]
